### ISSUE TITLE
Unable to use xclaim command

### ISSUE THREAD

**Issue by thapagorn-top** [WasabiThumb/xclaim#148]
Unable to use xclaim command

server Paper version 1.21.1

Errors displayed in the console

[22:19:27 ERROR]: Command exception: /xclaim
org.bukkit.command.CommandException: Unhandled exception executing command 'xclaim' in plugin XClaim v1.15.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.AssertionError: Layout loader threw a fatal exception
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts.throwFatal(GuiLayouts.java:142) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts.get(GuiLayouts.java:76) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiInstance.setSpecInternal(GuiInstance.java:60) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiInstance.open(GuiInstance.java:28) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiManager.openGui(GuiManager.java:61) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.command.sub.GUICommand.execute(GUICommand.java:49) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.command.Command.execute(Command.java:20) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.command.XClaimCommand.execute(XClaimCommand.java:74) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.command.CommandManager$Handler.onCommand(CommandManager.java:114) ~[xclaim-1.15.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]        ... 27 more
Caused by: java.io.FileNotFoundException: C:\Users\Administrator\Desktop\MC%20test\MC%20HC\plugins\.paper-remapped\xclaim-1.15.0.jar (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213) ~[?:?]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152) ~[?:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts$LoadWorker.populateEntries(GuiLayouts.java:315) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts$LoadWorker.run(GuiLayouts.java:288) ~[xclaim-1.15.0.jar:?]

**Comment by RHX0R3** [comment]
Can confirm, I have the same issue.
