### ISSUE TITLE
Some plugins are disabled after activation.

### ISSUE THREAD

**Issue by erdembekci** [WasabiThumb/xclaim#53]
Version: 1.20.1-R0.1-SNAPSHOT
Some plugins are disabled when I Activate xClaim. Some of these are SkinsRestorer and AureliumSkills. Is there something I did wrong?
```
[06:26:51 INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.12
[06:26:51 INFO]: [SkinsRestorer] Detected Minecraft v1_20_R1, using MappingSpigotSkinRefresher.
[06:26:52 ERROR]: Error occurred while enabling SkinsRestorer v14.2.12 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Bukkit.getAsyncScheduler()'
        at net.skinsrestorer.shadow.aikar.commands.ACFFoliaScheduler.createLocaleTask(ACFFoliaScheduler.java:51) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.aikar.commands.BukkitCommandManager.<init>(BukkitCommandManager.java:132) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.aikar.commands.PaperCommandManager.<init>(PaperCommandManager.java:34) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.SkinsRestorerBukkit.createCommandManager(SkinsRestorerBukkit.java:488) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.plugin.SkinsRestorerShared.sharedInitCommands(SkinsRestorerShared.java:70) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.SkinsRestorerBukkit.initCommands(SkinsRestorerBukkit.java:330) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.SkinsRestorerBukkit.pluginStartup(SkinsRestorerBukkit.java:243) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.SkinsRestorerBootstrap.onEnable(SkinsRestorerBootstrap.java:31) ~[SkinsRestorer.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-31]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:566) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-31]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WasabiThumb** [comment]
This seems like an issue with SkinsRestorer.

**Comment by erdembekci** [comment]
Same in different plugins. xClaim fixes itself when I disable it. I think it looks like an xClaim sided issue.

**Comment by WasabiThumb** [comment]
@erdembekci Looks like ACF was patched. Wait for your plugin authors to build versions with the new version of ACF or build it yourself if you have the patience.
