### ISSUE TITLE
player can pick up GUI item "Enchanting table" and use

### ISSUE THREAD

**Issue by Laythy** [WasabiThumb/xclaim#66]
mc version paper 1.20.4 build 405 , java 20.
when player use command /xclaim, choosing "version"(the enchanting table), player can just pick it up and place/destory/use and the terminal error is as bellow:

[21:29:31 INFO]: Laythy issued server command: /xclaim
[21:30:45 ERROR]: Could not pass event InventoryClickEvent to XClaim v1.10.5
java.lang.ExceptionInInitializerError: null
        at codes.wasabi.xclaim.gui.page.MainPage.onClick(MainPage.java:166) ~[xclaim-1.10.5.jar:?]
        at codes.wasabi.xclaim.gui.GUIHandler.onClick(GUIHandler.java:140) ~[xclaim-1.10.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor551.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-405]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1547) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-6.0.52.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:246) ~[paper-1.20.4.jar:git-Paper-405]
        at codes.wasabi.xclaim.platform.spigot_1_12_2.SpigotPlatform_1_12_2.setOwningPlayer(SpigotPlatform_1_12_2.java:13) ~[xclaim-1.10.5.jar:?]
        at codes.wasabi.xclaim.gui.page.VersionInfoPage.<clinit>(VersionInfoPage.java:58) ~[xclaim-1.10.5.jar:?]
        ... 26 more
>
![Uploading 2024-02-05_21.37.47.png…]()

**Comment by WasabiThumb** [comment]
Looks like someone took it upon themselves to [fix this issue](https://github.com/PierreSchwang/xclaim/releases/latest). Feel free to use this branch until v2 is done (i've been busy :/).

**Comment by PierreSchwang** [comment]
> Looks like someone took it upon themselves to [fix this issue](https://github.com/PierreSchwang/xclaim/releases/latest). Feel free to use this branch until v2 is done (i've been busy :/).

I can address a few issues and PR them to your Repo if you'd like that. Not sure if that's a bit less work for you in that case.

**Comment by WasabiThumb** [comment]
> > Looks like someone took it upon themselves to [fix this issue](https://github.com/PierreSchwang/xclaim/releases/latest). Feel free to use this branch until v2 is done (i've been busy :/).
> 
> I can address a few issues and PR them to your Repo if you'd like that. Not sure if that's a bit less work for you in that case. 

Sure, feel free, I'm working on V2 either way in my little free time but I'm sure the people currently stuck on V1 would appreciate that and definitely feel free to add your name to the About as this would be the first major code contribution from anyone else (other contribs  are language packs & build system updates)
